### ISSUE TITLE
informe

### ISSUE THREAD

**Issue by roy350** [IIC2133-PUC/2017-2#11]
Hola!, disculpa pero no me queda muy claro sobre que poner en el informe, que enfoque darle, sobre todo en el punto, uso de memoria, yo soy la persona que no uso malloc, esto que no va directamente relacionado con eso? o en el caso de una matriz estatica que debo hablar sobre el uso de memoria? simplemente que es estatica? si me pudieras explicar un poco mas sobre los detalles del informe te lo agradeceria mucho! perdon por molestar tanto :(

**Comment by Ghoeb** [comment]
La cantidad de memoria usada por tu programa es independiente de donde se guarda esa memoria: si usas malloc, se va a guardar en el _heap_, si no, se guardará en el _stack_, pero la cantidad de bytes es la misma.

El enfoque que debes darle a tu informe debe ser siempre teniendo en mente la eficiencia de tu programa, tanto en tiempo como en espacio. Mientras entres en los temas mencionados en el enunciado.
