### ISSUE TITLE
Error al Compilar

### ISSUE THREAD

**Issue by Rudyjb24** [IIC2133-PUC/2017-2#12]
Al utilizar el comando make me aparece el siguiente error (resumido):  
src/beholder/main.c:1:21: fatal error: gtk/gtk.h: No existe el archivo o el directorio
 #include <gtk/gtk.h>

Tengo entendido que esto tiene que ver con  el GTK 3. Realice la instalación como decía en la guia proporcionada. Estoy utilizando el Linux Subsystem en Windows.

**Comment by Ghoeb** [comment]
¿Qué pasa cuando pones el siguiente comando en consola?
```bash
pkg-config --cflags --libs gtk+-3.0
```

**Comment by Rudyjb24** [comment]
Me entrega el mensaje:
Package gtk+-3.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gtk+-3.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gtk+-3.0' found

**Comment by Ghoeb** [comment]
Ok, ejecuta el comando

```
cd /usr/include/gtk-3.0/ && ls
```

Y dime que imprime

**Comment by Rudyjb24** [comment]
Dice bash: cd: /usr/include/gtk-3.0/: No existe el archivo o el directorio

**Comment by Ghoeb** [comment]
Estás seguro que instalaste GTK usando
```
sudo apt-get install libgtk-3-dev
```

Como salía en la guía?

**Comment by Rudyjb24** [comment]
Si lo habia instalado pero lo instale de nuevo por si acaso y corri el comando de nuevo ahora me dice:
gdk  gtk  unix-print.

Ahora si me compila gracias pero al correr el ejecutable deberia abrir una pantalla de visualizacion?

**Comment by Ghoeb** [comment]
Para abrir la ventana en windows debes usar XMING. Sale al final de la guía.

**Comment by Rudyjb24** [comment]
Ya instale XMING pero al poner el comando export DISPLAY=:0 por consola no pasa nada.

**Comment by Ghoeb** [comment]
Tienes que abrir XMING desde windows primero, luego hacer export, y luego ejecutar tu programa.

**Comment by Rudyjb24** [comment]
Gracias

**Comment by vacodoceo** [comment]
Hola, tengo el mismo problema, pero al ejecutar el comando 

`sudo apt-get install libgtk-3-dev`

me retorna 

`-pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/mirclient -I/usr/include/mircore -I/usr/include/mircookie -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0
`

**Comment by jpdattas** [comment]
Hola tengo el mismo problema en con subsistema linux en windows.

Al hacer --cd /usr/include/gtk-3.0/ && ls-- , también me sale --gdk gtk unix-print--

Instalé GTK usando --sudo apt-get install libgtk-3-dev-- y antes y después de abrir Xming (porsiacaso) puse los comandos --export LD_LIBRARY_PATH=/usr/include/gtk-3.0/-- y --export DISPLAY=:0--

al hacer --make main-- me devuelve
--main.c:2:21: fatal error: gtk/gtk.h: No such file or directory
 #include <gtk/gtk.h>
                     ^
compilation terminated.
make: *** [main] Error 1--

**Comment by Ghoeb** [comment]
@jpdattas `make main` no es el comando correcto, deberías hacer solamente `make`.

**Comment by jpdattas** [comment]
seguro? al hacer `make` me devuelve `*** No targets specified and no makefile found.  Stop.`

Y `make main` me funcionaba en la carpeta "C"

**Comment by Ghoeb** [comment]
Verifica que esté la Makefile en la carpeta en la que estás, dado que sino `make` no funciona.

**Comment by jpdattas** [comment]
jaja perfecto. ahora entendí 😄
