### ISSUE TITLE
Duda valgrind

### ISSUE THREAD

**Issue by roy350** [IIC2133-PUC/2017-2#13]
Hola! disculpa pero me queda una duda en el valgrind me arroja esto 
![captura de pantalla 2017-08-20 a la s 13 19 59](https://user-images.githubusercontent.com/20785160/29496513-65b4b3d2-85aa-11e7-8eb8-2587e28ee5bd.png)
"still reachable: 552 bytes in 1 blocks" y no se si eso esta correcto y si es un problema con que tiene que ver? disculpa las molestias y que estes muy bien :)

**Comment by Ghoeb** [comment]
Es un tipo de memory leak, asique deberías arreglarlo (es el menos malo, pero igual). Usa el flag que te dice: `--leak-check=full` para saber donde está.

**Comment by roy350** [comment]
lo solucione!!! simplemente se me habia olvidado cerrar el archivo ahora esta todo correcto! muchas gracias!
