### ISSUE TITLE
Dudas sobre la base

### ISSUE THREAD

**Issue by vclaro1** [IIC2133-PUC/2017-2#15]
Hola!

corri lo que tiene la base y me tira memory leak... sin editar nada me dice esto:

<img width="567" alt="screen shot 2017-08-21 at 10 43 06 am" src="https://user-images.githubusercontent.com/11503037/29521984-1f833866-865e-11e7-9d22-5c295e9eed81.png">

Esto es parte de la libreria? o no esta tan corregido lo escrito?

**Comment by Ghoeb** [comment]
En que sistema operativo lo estas corriendo?

**Comment by vclaro1** [comment]
OSX Sierra

**Comment by fringlesinthestreet** [comment]
Es común que en OSX hayan falsos positivos :P

**Comment by fgvenegas** [comment]
Tambien me paso, probandolo en Linux sale lo correcto

**Comment by vclaro1** [comment]
Lo revisare con ubuntu entonces! gracias
