### ISSUE TITLE
Duda sobre informe de ejemplo

### ISSUE THREAD

**Issue by roy350** [IIC2133-PUC/2017-2#17]
Hola por ahi oi que subirian un informe de ejemplo, esto es verdad o nada que ver, disculpen la informalidad de la issue pero es para poder comparar mi informe con otro. Muchas gracias de antemano!!

**Comment by Ghoeb** [comment]
Hola, lo subi ahora. La demora se debió a que no encontrabamos informes anteriores que no les dieran literalmente las respuestas para las tareas de este semestre, o trataran con problemas tan distintos que leer el enunciado ya fuera un problema.

**Comment by iguridi** [comment]
Revisé la carpeta "2017-2/Tareas/Informes de ejemplo" y solo encontre un enunciado de una tarea del 2015-1. Están en otro lugar los informes de ejemplo? O aún no han sido subidos?

**Comment by roy350** [comment]
@iguridi es el que esta adentro de la carpeta informes de ejemplo pero afuera de enunciados se llama "Tarea 1 - 2015.1.pdf" :)

**Comment by roy350** [comment]
@Ghoeb muchas gracias!!
