### ISSUE TITLE
Liberacion de Memoria

### ISSUE THREAD

**Issue by Rudyjb24** [IIC2133-PUC/2017-2#18]
En el ejemplo de lista ligada vimos como liberar la memoria de los nodos y luego de la lista de manera recursiva.
Cuando yo creo mis propias estructuras de datos creo también una función liberadora de memoria adaptada a mi estructura. Hay alguna manera de asegurarme que mi función liberadora de memoria funciona correctamente, es decir que libera toda la memoria que solicite?

**Comment by Ghoeb** [comment]
Para eso está **valgrind** :wink:
