### ISSUE TITLE
Duda sobre soluciones parciales para tests (bullet bill)

### ISSUE THREAD

**Issue by aaferman** [IIC2133-PUC/2017-2#19]
Porque la solución de bullet bill genera bacterias en el lado izquierdo, si son zonas despobladas?
Especialmente en la esquina superior izquierda. 

bullet_bill.txt vs bullet_bill_1.txt

<img width="130" alt="bullet_bill" src="https://user-images.githubusercontent.com/8892424/29633556-0b7efac4-881d-11e7-8c3b-459270b87b5b.png">  <img width="143" alt="bullet_bill_1" src="https://user-images.githubusercontent.com/8892424/29633557-0bbd626e-881d-11e7-9312-8a11d0f488d9.png">

Gracias!

**Comment by Ghoeb** [comment]
Porque no son despobladas: las celdas de las orillas son vecinas entre ellas, ya que la superficie es un toro.

De manera más burda, al salirte de la matriz por un lado, vuelves por el otro, por lo tanto, la celda 0,0 tiene como vecino a la izquierda celda 0, w-1

**Comment by aaferman** [comment]
Toda la razón, gracias por aclarar!
