### ISSUE TITLE
Configuración Interfaz Gráfica

### ISSUE THREAD

**Issue by Ghoeb** [IIC2133-PUC/2017-2#2]
Para poder hacer funcionar la interfaz gráfica, deberás la librería correspondiente en tu computador.

[Esta guía](https://github.com/IIC2133-PUC/2017-2/wiki/4.-Setup-GTK--3) te explicará paso a paso como hacerlo.

**Comment by GerardoOlmos** [comment]
Tengo problemas con la interfaz gráfica, me funciona perfecto en Mac pero en Linux no funciona del todo bien.
Comienza a ejecutar, pero después de algunas iteraciones (depende de cuantas le entregue como input y del archivo.txt), se detiene mientras el programa sigue y finaliza sin errores.
Corrí valgrind y no tiene memory leaks.

**Comment by Ghoeb** [comment]
No hay problema con eso. Efectivamente a veces pasa que se detiene la interfaz, pero queda fuera de nuestro alcance. No afecta en absoluto lo que está pasando por detrás, asi que tu tranquilo 😉

**Comment by tblatrille** [comment]
@Ghoeb La interfaz no me funciona en mac pero si en linux, simplemente en mac no lanza la pantalla beholder, ¿qué me recomendarías hacer?
