### ISSUE TITLE
Duda Manejar Inputs Incorrectos

### ISSUE THREAD

**Issue by fringlesinthestreet** [IIC2133-PUC/2017-2#20]
¿Hay que preparar el programa para recibir input's incorrectos? ya sea un path que no lleva a nada o que el número de iteraciones no sea un número entero.

**Comment by fvr1** [comment]
No! Puedes asumir que el input siempre será de la forma descrita en el enunciado.

**Comment by fringlesinthestreet** [comment]
@fvr1 yap, gracias!
