### ISSUE TITLE
Posible problema de interfaz

### ISSUE THREAD

**Issue by cggutierrez** [IIC2133-PUC/2017-2#21]
Al momento de ejecutar mi tarea, cada iteracion me aparece de la manera correspondiente y valgrind me  retorna que tengo 0 errores, pero en ciertas ocasiones,  al ejecutar el programa solo carga un par de iteraciones y pero el sleep que le pongo entre iteraciones no se ve afectado y valgrind sigue diciéndome que no tengo errores.

Es posible que la interfaz tenga problemas y al ejecutarla aveces no actualice los pixeles? ya que me parece raro que el mismo test archivo funcione bien el 90% de las veces y el 10% se queda estancado en alguna iteracion

Gracias!

**Comment by Ghoeb** [comment]
En la práctica no correjiremos usando la ventana, sino leyendo las llamadas a las funciones `watcher` que la controlan.

De todos modos, es normal que al enviar muchas actualizaciones a la ventana en muy poco tiempo esta se "atonte", tiene que ver con GTK y está fuera de nuestro control, pero esto no va a afectar la corrección de tu tarea.

**Comment by cggutierrez** [comment]
Vale, gracias!
