### ISSUE TITLE
Algunos test solo me funcionan con valgrind

### ISSUE THREAD

**Issue by augustoal** [IIC2133-PUC/2017-2#22]
En algunos tests (parece que son los mas grandes) la imagen solo se me actualiza una vez cuando corro el programa normal, sin embargo cuando lo corro con valgrind todo funciona bien. Por que puede ser? Los otros test me funcionan bien.

**Comment by Ghoeb** [comment]
Valgrind y las interfaces gráficas no son amigos, así que es normal que haya diferencias en funcionamiento. Pero lo normal es que con valgrind funcione peor que sin valgrind.... seguro que valgrind dice que no hay problemas?

**Comment by augustoal** [comment]
Si, valgrind me dice que no hay problemas y me muestra todas las iteraciones. Lo estoy corriendo en una máquina virtual de Ubuntu en un Mac, tendrá algo que ver con eso?

**Comment by Ghoeb** [comment]
Es posible, las maquinas virtuales se comen una parte de los recursos del computador. Si valgrind dice que todo está bien, y estás calculando las generaciones correctamente, entonces deberías poder dormir tranquilo 😉

**Comment by augustoal** [comment]
Jaja dale gracias
