### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by lefischer** [IIC2133-PUC/2017-2#23]
Hola,

llevo mucho tiempo intentando hacer que me funcione pasar de generación, no entiendo por que no se me actualiza la imagen.

mi código esta subido

**Comment by aaossa** [comment]
Quizás te falta usar watcher_refresh() (está en el enunciado el detalle)
después de cambiar el estado de una posición con watcher_set_cell()

**Comment by lefischer** [comment]
hola,

si uso watcher_refresh(),
como que el código no me entra a un for que tengo

**Comment by Ghoeb** [comment]
Y probaste correrlo sin usar la interfaz gráfica? Que dice valgrind al respecto?
