### ISSUE TITLE
Invalid read

### ISSUE THREAD

**Issue by ndleyton** [IIC2133-PUC/2017-2#25]
Hola, al correr mi programa con valgrind me tira un error que al buscar en stackoverflow, me dice que es una especie de "index error", sin embargo, tengo varios if para reconocer si el indice está dentro de los parámetros.
![screenshot from 2017-08-24 15-18-13](https://user-images.githubusercontent.com/20179825/29682029-95b1c28e-88d7-11e7-86db-f1a3431385c0.png)
Si alguien le puede ganar a stackoverflow y ayudarme en esto, lo apreciaria mucho

PD: mi programa excelente de igual manera, por lo que me parece muy raro

**Comment by Ghoeb** [comment]
Quiero ver tu calloc, ese de la linea 111 del main.c
