### ISSUE TITLE
Error compilando

### ISSUE THREAD

**Issue by jpdattas** [IIC2133-PUC/2017-2#26]
Hola, compilando la carpeta recién clonada sin ningún cambio me funciona. Pero al editar Programa/src/main.c , make me devuelve errores.
``/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/crt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
collect2: error: ld returned 1 exit status
make: *** [simulate] Error 1``

Llevo mucho tiempo y todavía no entiendo por que pasa esto. Incluso si deshago los cambios y hago `make clean`, me sigue tirandoo el mismo error.

**Comment by Ghoeb** [comment]
Ese error dice que dentro de la carpeta `simulate` no hay ningun archivo .c que tenga una funcion main. Estás borrando la función main, o cambiando su firma?

**Comment by jpdattas** [comment]
Cambiando tan solo los valores 5 y 7 (de row y col) me pasa esto. Estoy usando el subsistema de linux en windows, por si acaso

**Comment by jpdattas** [comment]
De hecho, al dejar el main.c como estaba antes, sigue tirando el error.

**Comment by Ghoeb** [comment]
Sube el código a tu repo, probaré compilarlo en mi computador

**Comment by jpdattas** [comment]
Hay otro error con git también.

Al usarlo me tira `fatal: index file open failed: Input/output error`

**Comment by Ghoeb** [comment]
...

Y reiniciando tu computador? Si Linux Subsystem no te funciona, entonces tienes que usar una máquina virtual...

**Comment by jpdattas** [comment]
reinicié. borré la carpeta y cloné de nuevo. después hice `ls -al .git/index` y me devolvió

`ls: cannot access .git/index: No such file or directory`

...creo que tendré que usar ubuntu

**Comment by Ghoeb** [comment]
Em.... creo que tu uso de comandos de git es el problema, no el sistema.

Deberías probar git usando `git status`

**Comment by jpdattas** [comment]
devuelve `On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean`

**Comment by jpdattas** [comment]
Ahora hice git status y después todo me sirvió. No se realmente por que. reinicié hartas veces y hice otras cosas. Ahora magicamente funciona git y compila bien

**Comment by jpdattas** [comment]
me volvió a pasar. Al parecer el problema es que al modificar archivos desde windows (atom desde windows), es probable que haya fallas en los archivos (y me pasó el 99% de las veces)

**Comment by Ghoeb** [comment]
Maldito windows. Bueno, te deseo suerte con tu plataforma
