### ISSUE TITLE
Error falso en Valgrind

### ISSUE THREAD

**Issue by ndleyton** [IIC2133-PUC/2017-2#27]
Hola, que sucede si valgrind arroja un error que por la lógica del programa no puede ocurrir (como algo que puede no estar inicializado, pero no puede ocurrir que no se inicialize), cuenta esto para la evaluación o puede ignorarse, ya que el error no puede ocurrir?

**Comment by Ghoeb** [comment]
Los errores que lanza valgrind son todos errores que podrían causar comportamiento impredecible en tu programa. Quizas en tu computador algo funciona bien, pero en el mio no, etc.

Cualquier error que valgrind arroje corriendo el programa en ubuntu se considera para la evaluación.
