### ISSUE TITLE
Problemas con setup de Valgrind en Windows

### ISSUE THREAD

**Issue by nicosoto0** [IIC2133-PUC/2017-2#3]
Estimados, 

Al intentar instalar Valgrind a través del bash en la terminal de Windous tengo un problema al descargar el código fuente de Valgrind. Lo que ocurre es que al realizar el comando:

svn co svn://svn.valgrind.org/valgrind/trunk valgrind

se comienza a descargar el código fuente, pero después de descargar los primero 20 archivos, la descarga se cae y envía los siguiente errores:

svn: E200030: sqlite[S14]: unable to open database file
svn: E200030: Additional errors:
svn: E200030: sqlite[S14]: unable to open database file

Pienso que es un problema de conexión de la página, dado que algunas veces alcanza a descargar más archivos que otras. He intentado ejecutar el comando muchas veces, pero nunca logra terminar la descarga completa antes de enviar el error. También he intentado ejecutar los siguiente comando en la lista de instrucciones de la instalación de Valgrind, pero al parecer con los archivos que se alcanzan a descargar no funciona :/. 

Mi pregunta finalmente es si hay alguna otra forma de descargar el código fuente de Valgrind para poder luego realizar la instalación del programa con el bash.

¡De antemano muchas gracias!

Saludos
Nicolás Soto

**Comment by Ghoeb** [comment]
Creo que debería servir el que tienen subido en la pagina oficial : http://valgrind.org/downloads/
