### ISSUE TITLE
Dudas enunciado

### ISSUE THREAD

**Issue by Pyralspite** [IIC2133-PUC/2017-2#30]
Hola, leí el enunciado y quedé con algunas dudas.
La primera es a que se refieren con la poda y heurística. Busqué en internet y creo que con poda se refiere a no seguir el "camino" si está malo, pero la definición de heurística no la entendí para nada. 
La segunda es si puede haber más de un par de terminales del mismo color.
Y la tercera es si siempre habrá una solución para el cableado, y que hacer en caso contrario.

Perdón si son preguntas muy obvias, pero prefiero asegurarme.
Saludos :3

**Comment by Ghoeb** [comment]
Hola, te contesto en orden:

1) Lo que entendemos por podas y heurísticas está detallado en la Guía de Backtracking subida en el repo.

2) No hay ninguna restricción que impida que hayan más de un par de terminales para un color dado, es más, varios de los tests ejemplifican eso.

3) Para todas las tareas siempre pueden asumir que el input está bien formado y siempre existe al menos una solución.

**Comment by Pyralspite** [comment]
Muchas gracias :)!

**Comment by fgvenegas** [comment]
Hola!

Pero si existe mas de un par de terminales, por ejemplo 3 terminales, mi algoritmo una vez que una 2 terminales debería seguir intentando encontrar mas terminales?

**Comment by Ghoeb** [comment]
@fgvenegas La cantidad de terminales para un mismo color no puede ser impar 😮 , ya que no hay ninguna pieza que divida cables.

**Comment by Ghoeb** [comment]
@fgvenegas Pero si son pares, entonces vas a tener que trazar más de un cable para ese color, y las componentes de ese color van a tener que pasar por _alguno_ de esos cables

**Comment by fgvenegas** [comment]
ahh tiene sentido, gracias!
