### ISSUE TITLE
Cantidad de terminales por color.

### ISSUE THREAD

**Issue by Mieynaudi** [IIC2133-PUC/2017-2#31]
Hola!

Puedo asumir que solo habrán 2 terminales por color en cada tablero?

Salu3!

**Comment by pdpino** [comment]
Hola!
No, no puedes asumir eso. Un ejemplo de un caso que no se cumple es el test del repo base "multiline.txt"

**Comment by Mieynaudi** [comment]
Gracias!, no había revisado ese ejemplo :/
