### ISSUE TITLE
Hubs y colores

### ISSUE THREAD

**Issue by IgnacioTobar** [IIC2133-PUC/2017-2#32]
Hola, en el archivo base que nos pasaron habían ciertos comentarios:

// Si es hub
// Y tiene una capacidad válida (2, 3 o 4) 

// Es un componente con color (que pueden ser 1,2,3,4,5,6 o 7)

Podemos asumir esto? O sea no hubs de 1, u otros colores aparte de esos? El enunciado no lo especifica.

**Comment by Ghoeb** [comment]
Si, pueden asumirlo, para eso están esos comentarios ;)
