### ISSUE TITLE
Tarea 1 Problema con GTK Mac

### ISSUE THREAD

**Issue by isipalma** [IIC2133-PUC/2017-2#33]
Hola!

Quería pedir ayuda sobre un problema con la librería gtk. Cuando trato de hacer make me aparece el siguiente error:
```
Package fontconfig was not found in the pkg-config search path.

Perhaps you should add the directory containing `fontconfig.pc'
to the PKG_CONFIG_PATH environment variable
Package 'fontconfig', required by 'cairo', not found
clang: warning: -lpng: 'linker' input unused [-Wunused-command-line-argument]
clang: warning: -lm: 'linker' input unused [-Wunused-command-line-argument]
In file included from src/beholder/animating/animation.c:6:
src/beholder/animating/animation.h:3:10: fatal error: 'gtk/gtk.h' file not found
#include <gtk/gtk.h>
         ^
1 error generated.
make: *** [obj/beholder/animating/animation.o] Error 1 
```

Llevo este problema desde la tarea 0 y he buscado en internet pero ninguna solución me ha servido todavía. Tengo mac Sierra.

Saludos y gracias de antemano

**Comment by Ghoeb** [comment]
Quizás simplemente el package manager no está haciendo bien su trabajo. Probaste instalando GTK con la guía oficial (es decir, descargar el código y compilarlo) ? Échale una mirada [aquí](https://www.gtk.org/download/macos.php) 😃
