### ISSUE TITLE
No me ha llegado invitacion a repo T01

### ISSUE THREAD

**Issue by rmant** [IIC2133-PUC/2017-2#34]
Hola! Aún no me llega la invitación para el repo de la tarea 1! 

Que puedo hacer al respecto?

Gracias!

**Comment by gafigueroa** [comment]
Te acabo de reenviar la invitación

**Comment by rmant** [comment]
Gracias!

**Comment by vacodoceo** [comment]
Hola ! a mi tampoco me ha llegado la invitación aun
