### ISSUE TITLE
Uso librería tarea 1

### ISSUE THREAD

**Issue by Pyralspite** [IIC2133-PUC/2017-2#35]
Hola, puedo ocupar la función memset de la librería string.h para asignar los valores por defecto que tendrá una matriz? Su largo depende de una variable, así que no me deja inicializar la matriz con esos valores.

**Comment by Ghoeb** [comment]
Si claro, pero no será mejor usar `calloc`?

**Comment by Pyralspite** [comment]
Preferí no trabajar con el heap por el tiempo que demora en comparación al stack. O para los tests con los que van a probar la tarea es irrelevante?

**Comment by Ghoeb** [comment]
Se demora notablemente? Nosotros resolvemos las tareas haciendo todo en el heap, asique podríamos decir que si, es irrelevante. Also, debugear el stack es más dificil, pq valgrind no tiene mucho control sobre él.

**Comment by Pyralspite** [comment]
No hice la comparación empírica entre las dos formas, sino que me basé en lo que sabía y tomé mis decisiones. A estas alturas prefiero no cambiarlo, ya que la otra forma está permitida, pero tendré muy en cuenta lo que me dijiste para las otras tareas. Muchas gracias :)
