### ISSUE TITLE
Sobre la dificultad de los tests

### ISSUE THREAD

**Issue by Pyralspite** [IIC2133-PUC/2017-2#37]
Hola, yo otra vez.
La dificultad de los tests es representativa de los que usarán para evaluarnos? 
Lattice, en específico, me está causando problemas. Este test es parte de los ultra difíciles o es lo mínimo que debería poder resolver nuestro programa?

**Comment by Ghoeb** [comment]
La dificultad de los tests que subimos efectivamente es la de los que usaremos para evaluar. Asique si, ese es el rango de los dificiles. Esperen tambien que probemos con un par de tests más grandes que los que les subimos.

Si sirve de consuelo, la dificultad de los tests es calibrada segun lo que logra resolver la pauta sin usar podas ni heuristicas (pero esta modelada para que cada operacion tome O(1)), asique si podan y usan heuristicas deberian ganarnos por mucho en tiempo ;)
