### ISSUE TITLE
Duda tiempo algoritmo

### ISSUE THREAD

**Issue by fgvenegas** [IIC2133-PUC/2017-2#38]
Hola! 

Si yo quiero hacer algo como esto 
```
while(escoja_un_nodo){
      int i = random(1,n);
      nodo = lista_nodos[i];
      if (nodo_cumple_requisitos(nodo)){
           break;
      }
}
```

En que tiempo se considera que se encuentra ese while?

**Comment by alopez7** [comment]
Depende completamente de las funciones que estás usando.
* ¿qué hace escoja_un_nodo?¿cómo lo hace?
* ¿lista_nodos es una lista ligada? En ese caso obtener el elemento "i" es O(tamaño de la lista)
*¿qué hace la función nodo_cumple_requisitos?¿cómo lo hace?

**Comment by fgvenegas** [comment]
Si en vez de `while(escoja_un_nodo)` hiciera `while(1)`, si lista_nodos fuera un array y nodo_cumple_requisitos estuviera en O(1) como quedaría? Mi duda es como afecta el random mas que nada, por ejemplo si siempre escogiera el mismo valor, eso terminaria afectando en cuanto esta el tiempo del algoritmo?

**Comment by alopez7** [comment]
Puedes asumir que elegir un número random es O(1), el problema es que puedes repetir el mismo nodo varias veces. Asumiendo que al menos hay un nodo que cumple los requisitos, la esperanza es que saques un nodo que sirve en O(n). Así que puedes asumir que en conjunto es O(n)

**Comment by fgvenegas** [comment]
Vale gracias!
