### ISSUE TITLE
Problemas al ejecutar valgrind

### ISSUE THREAD

**Issue by Rudyjb24** [IIC2133-PUC/2017-2#39]
Cuando trato de utilizar valgrind me aparece un error muy largo  que puedo copiar si necesitan. Lo que entendi del error es que tengo que instalar glibc's debuginfo package. Pero cuando intento hacerlo con el comando sudo apt install libc6-dbg, la descarga falla con el error E: No se ha podido localizar el paquete libc6-dbg.

Estoy usando Linux Subsystem en Windows.

**Comment by alopez7** [comment]
Plz dame el output de cuando usas valgrind y cuando tratas de instalar libc6-dbg

**Comment by Ghoeb** [comment]
Normalmente los nombres de los paquetes a instalar no son el nombre de la librería, no me sorprendería que el paquete realmente se llamara `libc6-dbg-lib` o algo así. Revisa las sugerencias que te da `apt` al escribir (usando tab)

**Comment by Rudyjb24** [comment]
Se arreglo mi problema, efectivamente tenia que instalar libc6-dbg, por alguna razón ahora no me tiro error. Esta funcionando valgrind. Gracias.
