### ISSUE TITLE
Duda con valgrind

### ISSUE THREAD

**Issue by fgvenegas** [IIC2133-PUC/2017-2#4]
Hola!

Probe el codigo que nos dieron con valgrind y me arroja esto 
![captura de pantalla 2017-08-11 a las 8 50 07 p m](https://user-images.githubusercontent.com/13748708/29236295-c83b2156-7ed6-11e7-9e56-a8072a1edb1e.png)

Es "normal" que ya tenga errores o hice algo mal ? 

Salu2

**Comment by Ghoeb** [comment]
En que plataforma lo estas corriendo?

**Comment by fgvenegas** [comment]
Mac, en la versión de El Capitan, me dijeron que ahí funcionaba valgrind D:

**Comment by Ghoeb** [comment]
Valgrind "funciona", pero en Mac siempre va a entregar falsos positivos. Si quieres trabajar en Mac, asegurate de revisar que es lo que entrega valgrind con un programa vacío y luego revisas que sea eso lo que está reclamando. Por eso en la guía dice que deberias probar tu programa en linux de todos modos.

**Comment by fgvenegas** [comment]
Oka gracias
