### ISSUE TITLE
Programación modular en C

### ISSUE THREAD

**Issue by jpdattas** [IIC2133-PUC/2017-2#41]
Hola, todo lo que hagamos debería quedar en el main?

No sería conveniente poder hacer modulos con structs o funciones? 

Si fuera conveniente, como se haría para que funcionaran? habría que modificar el makefile?

**Comment by Ghoeb** [comment]
Para nada, lo ideal es que lo separen en varios archivos, como se ejemplificó en la primera ayudantía donde vimos listas ligadas. Puedes revisar el código que subimos [en el repo principal](https://github.com/IIC2133-PUC/2017-2/tree/master/Ayudantias/Ayudantia%200)

La Makefile ya viene configurada para que puedas compilar todos los archivos separados de tu programa, siempre que los mantengas en la carpeta `planner`.

**Comment by jpdattas** [comment]
ok muchas gracias. el problema era que dejaba las carpetas fuera de planner
