### ISSUE TITLE
Notas Tarea 0

### ISSUE THREAD

**Issue by fcgfaura** [IIC2133-PUC/2017-2#42]
Hola, cuándo estarán las notas de la tarea 0? 😲

**Comment by Ghoeb** [comment]
Deberían estar este jueves.

**Comment by fcgfaura** [comment]
Y qué pashó? 😲, y el enunciado de la tarea 2 cuándo la subirán ??

**Comment by Ghoeb** [comment]
Lo que pashó es que estaban todos los resultados, pero no estaban calculadas las notas. Pero ahora sí.

La tarea 2 será publicada el próximo jueves.
