### ISSUE TITLE
Tests Corrección T0

### ISSUE THREAD

**Issue by Ghoeb** [IIC2133-PUC/2017-2#45]
Para ayudarlos a identificar sus errores en la T0, se subieron los tests que fueron usados en la corrección.

Los tests fueron probados con 10 y 60 iteraciones, de ahí que sean 12.

El archivo `test_i` corresponde en la planilla a
* `test_i` con 10 iteraciones
* `test_(i+6)` con 60 iteraciones

**Comment by Ghoeb** [comment]
Los tests están junto al enunciado, [aquí](https://github.com/IIC2133-PUC/2017-2/tree/master/Tareas/Tarea%200/tests_correccion)

**Comment by fgvenegas** [comment]
Una duda, para los temas de tiempo, deberiamos sacar el watcher refresh ademas de los sleep o deberia bastar con los sleeps?

**Comment by oevasque** [comment]
Solo los sleep, cuando hacen refresh se escribe el resultado por lo cual no lo deben quitar.

**Comment by cggutierrez** [comment]
Que tanto se puede modificar el código para recorregir? es valido cambiar una estructura y arreglar el código para que funcione con esta?

**Comment by oevasque** [comment]
Pueden modificar las lineas que quieran, pero deben recordar que hay descuento por linea agregada o cambiada
