### ISSUE TITLE
Error Tarea0 en watcher_open

### ISSUE THREAD

**Issue by jfcumsille** [IIC2133-PUC/2017-2#46]
Hola! Estaba revisando los test con los que corrigieron la Tarea0 y desde el test_4 en adelante (con 10 y  60 iteraciones), me aparece error _Invalid write of size 8_ en la línea de watcher_open.
El error es este:
![screenshot_20170920_225802](https://user-images.githubusercontent.com/11492867/30675759-ac28305c-9e58-11e7-8db3-ead847340d6d.png)

Si uso --max-stackframe=10000016 y --main-stacksize=100000016 el error desaparece y el test_4 corre sin problemas. Sin embargo, para los otros test necesito números aún mayores para que funcionen.

![screenshot_2](https://user-images.githubusercontent.com/11492867/30676779-3b457998-9e5e-11e7-9ad8-57ea7b771b30.png)

Probé comentando las llamadas a watcher pero entonces el error cambia al fscanf que lee los 0 y 1 del input file.

Cualquier ayuda para saber que puedo hacer será muy agradecida ya que no sé como arreglar este problema para recorregir. 
Por si sirve de algo, los test del 1 al 3 funcionan al 100% en correctitud y uso de memoria.

Desde ya, muchas gracias.

**Comment by Ghoeb** [comment]
Hola, estás haciendo las matrices en el stack de memoria (usando corchetes)? Esos tests son más grandes de lo normal, por lo que es posible que a tu programa se le esté acabando el stack por eso. Prueba crear las matrices en el heap (usando malloc) y cuentame como te va.

**Comment by jfcumsille** [comment]
Muchas gracias! Con eso se solucionó el problema. Una última cosa, para las próximas tareas podrían darnos tests de dificultad más cercana a los que usaran en la corrección? El más complejo que tuvimos para esta tarea fue de 100x100 por lo que al probar mi tarea todo funcionaba bien y no pensé que podría llegar a fallar :(
Nuevamente, muchas gracias por la ayuda!
