### ISSUE TITLE
Recorreccion Tarea0

### ISSUE THREAD

**Issue by lsvargas** [IIC2133-PUC/2017-2#47]
Hola! me gustaría saber que es lo que tengo malo de mi tarea para así poder recorregir, hice pull al repositorio y corri la tarea y funciona con todos los test que dieron como ejemplo, pero en la planilla tengo puros 0 y no parece ningún error especificado en los comentarios.

Gracias Saludos

**Comment by oevasque** [comment]
Simplemente es porque los resultados que entregas no son correctos.

**Comment by lsvargas** [comment]
Tengo una duda dado este tablero cual de las formas es correcta segun el enunciado.
Tablero:     |1 0 1 |          1) |0 0 1|       2) |0 1 1|
                  |0 0 1|               |0 0 1|           |0 0 1|

cual es la opcion que deberia seguir la 1 o la 2 yo entendi que los cambios se realizan sobre el tablero original sin modificar y que no se va modificando por cada posicion que se va avanzando.

**Comment by oevasque** [comment]
Es un poco complicado el ejemplo dado el tamaño

1  0 0 1  0
1 |1 0 1| 1
1 |0 0 1| 0
1  1 0 1  1

El contador de vecinos entonces son:
|3 4 3|
|5 5 4|

Entonces el siguiente estado sería:
|1 0 1|
|0 0 0|
