### ISSUE TITLE
Cantidad de bacterias para poblar

### ISSUE THREAD

**Issue by fgvenegas** [IIC2133-PUC/2017-2#5]
En este punto 
![captura de pantalla 2017-08-12 a las 1 56 12 a m](https://user-images.githubusercontent.com/13748708/29238343-7efb1d40-7f01-11e7-883b-9c8045766ab7.png)

Tienen que ser exactamente 3 o pueden ser mas de 3 bacterias ? 

Gracias

**Comment by Ghoeb** [comment]
Deben ser exactamente 3

**Comment by fgvenegas** [comment]
Vale gracias !
