### ISSUE TITLE
Interfaz se pega (tarea2)

### ISSUE THREAD

**Issue by Zanfor** [IIC2133-PUC/2017-2#51]
Hola cuando trato de hacer cualquier loop dentro del programa base, se pega y no termina de cargar el archivo en el watcher (carga un numero intermedio de segmentos que varía segun la ejecución incluso para el mismo compilado). Sin embargo, si hago watcher_snapshot() me muestra como si la interfaz estuviese correcta (completa). Traté de usar sleeps para lidiar con esto pero no solucioonó el problema. Alguna idea de que puede ser? Es muy molesto trabajar asi porque no puedo ver las lineas que genero en tiempo real :/

**Comment by Ghoeb** [comment]
Hm.... en general esos problemas se arreglan poniendo sleeps. Quizas es un problema de tu computador, pero solo para confirmar, commitea tu código y lo reviso desde el mio.
