### ISSUE TITLE
Chequeo de Tests

### ISSUE THREAD

**Issue by Rudyjb24** [IIC2133-PUC/2017-2#53]
Esta subido a alguna parte o van a subir las imágenes de los test completados? Para poder revisar si lo que estamos haciendo esta bien.

**Comment by Rudyjb24** [comment]
Gracias por subir las fotos, es una buena manera de discriminar si nuestro output va por el buen camino. Sin embargo siento que es muy posible que pixeles no esten exactamente en el buen color y sea imposible discriminarlo simplemente comparando las fotos. como se evaluara, habrá algún programa que compara pixel a pixel nuestro output con la solución. De ser así podríamos tenerlo para revisar si estamos generando outputs correctos?

En otro tema, en el código que nos subieron los obstáculos se colorean con un gris 0.5 0.5 0.5, me da la impresión que las soluciones que subieron están pintadas con un gris mas oscuro. En caso de que ocuparan un programa como el que describí mas arriba eso afectaría la validez de nuestro output?

**Comment by alopez7** [comment]
Al revisar su output, no se van a considerar los obstáculos. Solo deben
preocuparse de colorear bien los pixeles según las luces.
Con respecto a la corrección, se comparará el color de todos los pixeles
con el de la pauta, y se calculará la diferencia. El 100% será cuando la
diferencia sea 0, y el 0% cuando la diferencia sea sobre cierto margen. Las
diferencias que sean entre el resultado perfecto y el margen de diferencia
se interpolarán. Eso quiere decir que si algunos pixeles están mal, pueden
tener porcentajes incompletos pero mayores a 0%

**Comment by Rudyjb24** [comment]
Gracias. Seria posible que nos presten el código que hará la comparación por pixel?
Para saber si esta bien lo que estamos haciendo.

**Comment by alopez7** [comment]
Acabo de subir un comparador de imagenes al repo, le das dos imagenes y te da la cantidad de pixeles distintos y genera una imagen nueva con al diferencia. Si la imagen es negra, la diferencia es 0. Ojo que el porcentaje de pixeles distintos no es la nota al monento de corregir, ya que el 0% es con menos pixeles distintos

**Comment by alopez7** [comment]
Está en Tareas/Tarea2
Se ejecuta como:
python3.5 comparer.py im1.png im2.png imgout.png

**Comment by fgvenegas** [comment]
Los segmentos es normal que me los tire como pixeles distintos? por el hecho de que tienen distinto color los de la tarea con los que ustedes subieron despues

**Comment by alopez7** [comment]
Es normal, igual no se va a corregir con segmentos. No se preocupen por eso
