### ISSUE TITLE
Duda mediana

### ISSUE THREAD

**Issue by fgvenegas** [IIC2133-PUC/2017-2#54]
Hola! 

Tengo una duda, si tengo un array como éste 
`{ 40, 10, 100, 90, 20, 25 }`
que ordenado sería: 
`{ 10, 20, 25, 40, 90, 100 }`

Mi mediana sería solo calcular ceil(25 + 40 / 2) = 33 ?
En verdad es una duda simple, pero prefiero asegurarme. 

Gracias!

**Comment by alopez7** [comment]
Si

**Comment by fgvenegas** [comment]
gracias!

**Comment by Ghoeb** [comment]
De hecho, técnicamente, ni siquiera es redondeando: la mediana de un grupo de numeros enteros puede ser racional.

**Comment by fgvenegas** [comment]
pero si lo redondeo puede afectar?

**Comment by Ghoeb** [comment]
Si, porque podrías tener que los datos son 

```c
{15,27,33,34,56,89}
```

Si redondeas te queda que la mediana es 33, por lo que el 33 queda EN la mediana, y por lo tanto, a ambos lados (o ninguno, o ve tu para donde lo mandas)

En cambio sin redondear queda 33.5, por lo que el plano divide el arreglo efectivamente en 2, sin tener que repetir elementos o decidir que hacer con los iguales.

**Comment by fgvenegas** [comment]
Oka voy a cambiarlo, gracias!
