### ISSUE TITLE
[T02] Dos algoritmos o basta uno? 

### ISSUE THREAD

**Issue by isipalma** [IIC2133-PUC/2017-2#57]
Hola!

Quería saber si es **estrictamente** necesario (para el informe) hacer un código que solape las cajas **y** otro que corte los segmentos para compararlos. Con el objetivo de compararlos entre ellos en cuanto a tiempo y datos empiricos.

O acaso solo basta hacer uno de estos y luego compararlo con el básico (el que se muestra en el enunciado)?

Saludos

**Comment by alopez7** [comment]
No es necesario explicar el código de esa parte,  debes comparar los tiempos ejecutando tu código muchas veces con ambos sistemas

**Comment by isipalma** [comment]
Gracias!

Eso si, te refieres a que no hay que explicar el codigo del enunciado?

Osea, en el informe debe estar: 
- explicacion de cada algoritmo que usa KDtree
- resultados de ambos sistemas
- analisis de tiempo y memoria

Me falta algo más que debiese tener el informe?

Saludos!

**Comment by alopez7** [comment]
En el informe se debe explicar el aproach que se dio al problema: ¿cómo solucionaste el problema? Dando código, pseudo código o una explicación completa de la estructura del programa. Además debes complementar esa explicación con imágenes para explicarlo mejor. Es bueno decir por qué se cree la solución implementada tiene la complejidad buscada.

En la parte de análisis empírico, se debe comparar la eficiencia (midiendo el tiempo) ejecutando el programa con distintos settings, y a partir de esto encontrar el modo de ejecución mas eficiente. Es bueno sacar conclusiones de estos datos y compararlos con lo que se dijo que se esperaba en el análisis teórico

**Comment by fgvenegas** [comment]
Pero al fin de todo tenemos que dejar una profundidad fija (harcodeada) que fue la que consideramos la "mejor" para cualquier mapa?

**Comment by alopez7** [comment]
Si, qunque no lo llamaría hardcodeada. En realidad es un criterio testeado que lo hace más eficiente
