### ISSUE TITLE
Formato Input

### ISSUE THREAD

**Issue by Rudyjb24** [IIC2133-PUC/2017-2#59]
Podemos asumir que en el input en cada linea correspondiente a los obstáculos, el primer punto es el de mas "arriba a la izquierda" y el segundo es el de mas "abajo a la derecha"?  Es decir que si una linea de recta es ax ay bx by, podemos asumir que ax <= bx y ay <= by?
Pregunto porque es importante en una de mis funciones y quiero saber si necesito darme la lata de revisar que esto sea el caso.

**Comment by Rudyjb24** [comment]
Ya me respondi, encontre un archivo que presenta la estructura que no queria.

**Comment by alopez7** [comment]
No necesariamente se cumple
