### ISSUE TITLE
[T2] Duda calculo aporte luz

### ISSUE THREAD

**Issue by nicosoto0** [IIC2133-PUC/2017-2#60]
Estimados,

Me quedaron dudas de como calcular el aporte de una Luz en un punto. Específicamente, el enunciado menciona que este dato se debe calcular con la formula:
C * (e ^ ( (-d^2) / (2*I^2) ))

donde C es el color de la luz en formato RGB. Revisando en Internet, el color de la luz en RGB se calcula con la formula:
C = R*256*256 + G*256 +B

Mi duda es como se hace para luego ingresar este dato a la función "watcher_set_color(R, G, B)" que recibe 3 parámetros y no uno. Tengo la intuición de que el aporte de una Luz debe calcularse independientemente para cada color, es decir:

aporte rojo    = aux_R    = R * (e ^ ( (-d^2) / (2*I^2) ))
aporte verde  = aux_G   = G * (e ^ ( (-d^2) / (2*I^2) ))
aporte azul    = aux_B    = B * (e ^ ( (-d^2) / (2*I^2) ))

y luego entregar a la función  dichos parámetros, o sea: "watcher_set_color(aux_R, aux_G, aux_B)"-

¿Estoy en lo correcto o no?. Si es que no, ¿como debe realizarse el calculo correcto?

De antemano gracias!
Nicolás

**Comment by alopez7** [comment]
El color RGB está dado por 3 valores de 0 a 1, (no de 0 a 255). Cuando multiplicas el color por un número, ppnderas el vector por el número (multiplicas componente a componente)

**Comment by nicosoto0** [comment]
Gracias!
