### ISSUE TITLE
Duda profundidad

### ISSUE THREAD

**Issue by fgvenegas** [IIC2133-PUC/2017-2#61]
¡Hola!

Cuando aumento la profundidad a la que dejo de comstruir el árbol, ¿es posbile que es demore más en pintar la imagen? O que a la misma pronfundiad ¿Pillars se demore menos que House 1? o tal vez ¿sólo es un error de mi programa 😢 ?

Gracias!

**Comment by alopez7** [comment]
Si fuerzas por ejemplo a que hayan 3 o menos segmentos por hoja (muy pocos), es posible que al dividir las cajas, estés dividiendo muchos segmentos, por lo que en la práctica los hijos se mantienen con casi la misma cantidad de hojas que el padre. Esto hace que el árbol sea innecesariemente profundo y por lo tanto la búsqueda se hace ineficiente. Debes buscar una profundidad que haga que minimice el tiempo, no necesariamente la profundidad optima es con muy pocos segmentos por caja
