### ISSUE TITLE
Tiempo de Ejecución 

### ISSUE THREAD

**Issue by Rudyjb24** [IIC2133-PUC/2017-2#63]
Cuanto es un tiempo es razonable para completar los tests? (En particular los test asteroids y firework que son los que mas lentos me corren)

**Comment by Ghoeb** [comment]
Lo que se pide en tiempo es ... harto más rapido que la versión sin el KD-Tree. Esto en base a las complejidades esperadas:

O(PLS) vs O(PL log S)
