### ISSUE TITLE
Uso de malloc

### ISSUE THREAD

**Issue by Rudyjb24** [IIC2133-PUC/2017-2#64]
Mi programa genera una enorme cantidad de errores del estilo "Invalid read of size 8". Estos errores no afectan el desarrollo de mi programa pero son muy molestos.

Me da la impresión que estos se generan porque estoy "anidando" estructuras con memoria reservada. Es decir tengo un struct A, al cual le hago un malloc de si mismo para reservar la memoria correspondiente. Luego creo un struct B que tiene como elemento una instancia de A, y también hago un malloc. 

Es posible que sea por esto que me este tirando error?

**Comment by Ghoeb** [comment]
valgrind te dice exactamente en la linea en la que se produjo el error. Que tal revisar ahi?

**Comment by pdpino** [comment]
Cabe mencionar que no sólo los errores son molestos, sino que con otros tests tu programa se puede caer.

**Comment by Rudyjb24** [comment]
Me tira error solo haciendo el init del struc "menos anidado" es decir el que contiene otros structs.

**Comment by Rudyjb24** [comment]
Esos son los primeros errores que me tira. Generalmente hablando, ¿es mala practica anidar estructuras?

**Comment by alopez7** [comment]
No es mala práctica. Tu tienes error de lectura porque estás leyendo fuera de tu memoria asignada. Esto puede ser por ejemplo por pasarte del largo de un arreglo o por inicializar un struct sin malloc en un scope y retornar el puntero de este.
