### ISSUE TITLE
Precision double

### ISSUE THREAD

**Issue by fgvenegas** [IIC2133-PUC/2017-2#65]
Hola,

Si caclulo los t1 y t2 para chequear interseccion y me entregan (al printear con %lf)
`t1: 1.000000 t2: 0.954796` , que es correcto ya que si hay interseccion, pero aun asi al hacer:
`if (0.0 <= t1 && t1 <= 1.0 && 0.0 <= t2 && t2 <= 1.0){}` no entra en el if, cual es el problema y como debería solucionarlo entonces :c?

En internet recomendaban [esto](https://stackoverflow.com/questions/11189026/comparing-double-variable-with-a-integer-value-in-c), pero no se si es lo mas correcto

gracias!

**Comment by Hernan4444** [comment]
A mi tambien me pasó esto y lo único que pude hacer fue lo siguiente:
![image](https://user-images.githubusercontent.com/15641721/31628954-8bb24d1e-b288-11e7-84e8-1736b63c6f4c.png)

Ojalá puedan ayudar a unas pobres almas desesperadas 😓 
Gracias!

**Comment by fgvenegas** [comment]
Probando escribir el if asi:
`if (0.0 <= t1 && t1 <= 1.00000001 && 0.0 <= t2 && t2 <= 1.00000001)`
soluciona el problema, pero siento que es una solución muy harcodeada :/

**Comment by fgvenegas** [comment]
Help :c

**Comment by jachicao** [comment]
Para los floats generalmente se usa un epsilon, fabs(t2 - 1) < DBL_EPSILON

**Comment by alopez7** [comment]
En general se suele agregar un epsilon para solucionar esto, sin embargo la solución no tiene los epsilons para hacer justa la corrección. Yo creo que si alguien tiene una diferencia por algo de ese tipo, se puede perdonar porque no es la parte importante de la tarea
