### ISSUE TITLE
Intersección de segmentos (Tarea 2)

### ISSUE THREAD

**Issue by selira** [IIC2133-PUC/2017-2#66]
Estimados Ayudantes:
En el anexo del enunciado dice que cuando dos segmentos son paralelos el determinante del sistema es 0, pero qué pasa cuando los segmentos son paralelos y coincidentes (o sea pueden tener más de un punto en común)? Cómo cálculo eso?
Gracias, saludos.

**Comment by Rudyjb24** [comment]
Da lo mismo, el determinante te dará 0 siempre que sean paralelas las rectas por lo cual se considera que no hay colisión. No necesitas hacerte cargo de si son paralelas con o sin puntos en común.

**Comment by selira** [comment]
cierto, ya lo habían contestado en #52 xD
