### ISSUE TITLE
Error raro

### ISSUE THREAD

**Issue by cggutierrez** [IIC2133-PUC/2017-2#67]
Hola, terminando de arreglar errores luego de escribir código me apareció este error que no se como solucionar, he revisado mi código varias veces y no logro encontrar el problema.

![image](https://user-images.githubusercontent.com/17582367/31652650-2df89ade-b2f6-11e7-9651-87abc9d1ae7d.png)

Todo lo que llevo de la tarea esta en el repo, por si es posible mirar el código y ayudarme a encontrar el error (perdón por el pésimo código, aun no me acostumbro a C y hago lo que puedo)

Muchas gracias!

**Comment by alopez7** [comment]
Es posible que tengas algun archivo de tu programa que se está importando dos veces, por lo que se define dos veces una función. 
Para evitar esto, pon #pragma once en los archivos .h y estructura tus archivos de manera de que los .c importen su archivo .h y los archivos .h se importen entre ellos.

**Comment by cggutierrez** [comment]
No modularise, tengo todo en el main.c :s

**Comment by Ghoeb** [comment]
Dos opciones: o efectivamente estás definiendo "is_visible" dos veces, o en algun lado la estás llamando con distintos parámetros que los de la definición.

**Comment by cggutierrez** [comment]
Por mas que reviso con  Ctrl + F en Atom no encuentro que puede estar mal, de hecho "distancias_cuadradas" no lo modifique y funcionaba perfectamente.

**Comment by Ghoeb** [comment]
Que pasa si haces `make clean` y luego `make` otra vez?

**Comment by cggutierrez** [comment]
practicamente lo mismo: 
![image](https://user-images.githubusercontent.com/17582367/31671251-ee4fbc98-b32f-11e7-8e8c-502713dfbc75.png)

**Comment by Ghoeb** [comment]
Hm, subelo a tu repo a ver si puedo ver que es.

**Comment by cggutierrez** [comment]
Ahí lo subí al repo, gracias!

**Comment by cggutierrez** [comment]
Ahi lo solucione, tenia guardado el código sin KDT como main1.c y el make intentaba compilar ambos a la vez.

Gracias!
