### ISSUE TITLE
Problema con "+" y "-"

### ISSUE THREAD

**Issue by cggutierrez** [IIC2133-PUC/2017-2#68]
Hola, tengo un problema en el manejo de doubles. Ncesito sumar 2 doubles pero por alguna razon, el segundo me lo considera como NaN, mientras que si intento restarlos, me los resta perfectamente. 
Este error ocurre solo al cambiar un "-" por un "+"  y nada mas del codigo. 

Intente multiplicar el primer numero  por -1 y restar para luego el resultado volver a multiplicarlo por -1 (intente sumar negativamente), pero el resultado siguio siendo el mismo y el segundo numero seguia tomandose como NaN.

Ayuda porfavor! :c

(especificamente, esto ocurre en las lineas 93 y 199 de mi codigo que ya esta en mi repo)

**Comment by Ghoeb** [comment]
Y, estás seguro que es la suma o la resta y no la división por un numero que podría ser 0?

**Comment by cggutierrez** [comment]
si, lo que me da problemas que por ejemplo:
``` c
double a = segmento.xi
double b = segmento.xf

double punto_medio = (a - b)/2

```
eso me tira el resultado correcto, por ejemplo si a = 2 y b= 3, me tira 1 en cambio de esta manera:

``` c
double a = segmento.xi
double b = segmento.xf

double punto_medio = (a + b)/2

```
punto_medio me tira que es NaN, y al printear a y b, b me sale que es NaN, entonces no entiendo cual es el problema y de donde surge
