### ISSUE TITLE
Problema codigo en C

### ISSUE THREAD

**Issue by lefischer** [IIC2133-PUC/2017-2#69]
Hola,

he estado probando los tests pero en asteroid1.txt se me cae y llevo mucho tiempo intentado descubrir porque, hay alguna forma de saber en que parte se cae (de hacer debug)?

**Comment by fgvenegas** [comment]
Estas liberando la memoria?

**Comment by alopez7** [comment]
Valgrind sirve para debuguear. 
Ejecuta valgrind ./solver scene.txt

**Comment by alopez7** [comment]
Y fíjate que en la makefile hay un flag que es nivel de optimización. Hay dos lineas, una comentada y otra no. Puedes dejar descomentada la que dice que es pare debuguear

**Comment by lefischer** [comment]
si libero la memoria

**Comment by alopez7** [comment]
Valgrind no es solo para ver la meloria, es para debuguear!

**Comment by Ghoeb** [comment]
Osea, `valgrind` SIRVE para debugear (al menos te dice exactamente donde se cae, y te avisa de los errores de memoria... que SUELEN traducirse en errores del programa)

Si quieres algo para debugear paso a paso y poder examinar los valores de las variables en un momento dado, aprende a usar `gdb`
