### ISSUE TITLE
Output T03

### ISSUE THREAD

**Issue by Hernan4444** [IIC2133-PUC/2017-2#70]
Hola! 
 El enunciado dice que:
> El output de tu programa es mostrar correctamente la imagen en su estado resuelto.  Se medirá la cantidad de operaciones que hayas enviado a la interfaz....

Lo anterior implica que medirán solo los `operation_watch(operation)` que usemos??
Es caso que la respuesta es si, no será un handicap adicional el tiempo que se demora la interfaz en aplicar cada operación?

Esto lo pregunto para saber si es necesario considerar dentro de los 10 segundos el tiempo de aplicar cada operación o basta con saber que usando `operation_print(operation)` la solución debe ser menor a 10 segundos.

Gracias de antemano! ✌️

**Comment by alopez7** [comment]
Mediremos las llamadas a la función, pero no te preocupes del tiempo que demora la interfaz, ya que al corregir se cambia la librería watcher por otra librería del mismo nombre cullos métodos ayudan a corregir y no se demoran
