### ISSUE TITLE
Repo T03

### ISSUE THREAD

**Issue by ndleyton** [IIC2133-PUC/2017-2#71]
Hola, me pueden asignar un repo para la Tarea 3? :)

**Comment by gafigueroa** [comment]
Hola, al parecer no te llegó la invitación.
Intenta metiéndote a este link, https://github.com/IIC2133-PUC/ndleyton-T3-IIC2133-PUC-2017-2

**Comment by gafigueroa** [comment]
Por si alguien más revisa esta issue ya que no tiene repo, si no les llega la invitación intenten metiendose al link:
https://github.com/IIC2133-PUC/usuario-TX-IIC2133-PUC-2017-2
reemplazando usuario por su usuario de GitHub y la X por el numero de la tarea.

**Comment by ndleyton** [comment]
Muchas Gracias, está bueno saber lo último
