### ISSUE TITLE
Uso de lista ligada de la ayudantia 0

### ISSUE THREAD

**Issue by roy350** [IIC2133-PUC/2017-2#72]
Hola, es posible usar el código de lista ligada entregado en la ayudantía 0, con leves modificaciones?, si es así se debe citar? o debo crear una lista ligada desde 0? muchas gracias de antemano :)

**Comment by alopez7** [comment]
Puedes usarlo. Ya que no hay informe, no es importante que lo cites. Gracias por preguntar.

**Comment by roy350** [comment]
de nada! muchas gracias :)
