### ISSUE TITLE
Tarea 3 Problema probando main

### ISSUE THREAD

**Issue by lsvargas** [IIC2133-PUC/2017-2#73]
Hola al probar como funcionaba el la interfaz me tira core dumped.
![image](https://user-images.githubusercontent.com/11396574/32130372-772a930e-bb6d-11e7-9800-796018cd3447.png)
Y luego lo ejecuto con valgrind y me tira lo siguiente:
![image](https://user-images.githubusercontent.com/11396574/32130386-95c6cf4e-bb6d-11e7-8e18-ee6b864bba6a.png)

**Comment by alopez7** [comment]
En qué sistema operativo estás?

**Comment by Ghoeb** [comment]
Se te abre la ventana al principio al menos?

**Comment by lsvargas** [comment]
En ubuntu 16.10 y si se me abre la ventana hace el primer flip y luego se cae

**Comment by Ghoeb** [comment]
Prueba abrir la ventana directamente:

```
./beholder imgs/img_1.png 4 4
```

Y luego escribe en consola

```
R 0
R 0
X
```

**Comment by lsvargas** [comment]
Todo bien cuando se abre la imagen pero al ejecutar el primer R 0, se ve como gira la fila hasta cierto punto y luego Aborted (core dumped) :S

**Comment by Ghoeb** [comment]
Perfecto. Ahora haz eso mismo pero con valgrind, para saber donde se cayó

```
valgrind ./beholder imgs/img_1.png 4 4
```

**Comment by Ghoeb** [comment]
Advierto que valgrind va a tirar mucho ruido por librerías que usa GTK, fijate solo en donde se cae, debería ser la última alerta

**Comment by lsvargas** [comment]
![image](https://user-images.githubusercontent.com/11396574/32131431-33f3fb2c-bb84-11e7-8d8a-77ad73285742.png)

**Comment by Ghoeb** [comment]
Y no tuviste problemas con las interfaces anteriores? A menos de que estés compilando con -O3 (fijate en la Makefile), eso parece ser directamente un error de GTK. Lo unico que se me ocurre es desinstalar GTK y volverlo a instalar...

**Comment by Ghoeb** [comment]
Probé tu programa en tu repositorio, y con los tests que probé los resuelve correctamente, pero tu programa se cae (aunque no interactue con la ventana). Preocupate de dejarlo funcionando sin la ventana, y de ahi podemos arreglar el resto.

Me llama la atención un print que haces que imprime `C 48`.

Lo otro, no estabas corriendo sobre Ubuntu? Por qué subiste los archivos .DS_Store, exclusivos de MacOS?

**Comment by lsvargas** [comment]
Si ubuntu! que raro quizas te equivocaste de repo porque no he hecho ningun push,
https://github.com/IIC2133-PUC/lsvargas-T3-IIC2133-PUC-2017-2, sii por mientras he estado avanzando en el codigo (sin interfaz)

**Comment by alopez7** [comment]
Sorry, eso fue culpa mía, estaba revisando otro repo y le dije a vicho que te responda. Fue una confusión.
