### ISSUE TITLE
Duda con recorrecciones

### ISSUE THREAD

**Issue by MortizDX** [IIC2133-PUC/2017-2#74]
Tengo dos dudas a la hora de pedir recorrección del código de la tarea:
1. ¿Qué exactamente vale como un cambio en un statement? (en el sentido de que si hay varias operaciones en una linea juntos, por ejemplo).
2. Los cambios que van a revisar ¿solo son los de la rama principal? ¿importa si hacemos cambios en otras ramas?

**Comment by Ghoeb** [comment]
Tengo dos respuestas, una para cada una de tus dudas 😄 

1. Un _statement_ es una instrucción, ya sea de control de flujo, asignación de una variable o llamada a una función, entre otras. Para responder a tu duda, la composición de _statements_, en este caso funciones, cuenta como un solo _statement_. (hint: todo lo terminado en `;` o `{` es un _statement_). Contrario a lo que parece ser, no tiene que ver con la cantidad de lineas: por una cosa de legibilidad uno trata siempre de tener un solo statement por linea, pero a la hora de compilar eso no importa.
2. Nosotros revisamos lo que ustedes tengan en la rama `master`, así que no, haz lo que se te de la gana con las otras ramas 🎉 

Respecto al descuento, cada _statement_ modificado descuenta 0.1, pero mover un _statement_ de un lugar a otro lo consideramos como una sola modificación (y no como un borrar el _statement_ y agregar ese mismo _statement_ en otro lugar), así que solo descuenta 0.1

Saludos!

**Comment by MortizDX** [comment]
Gracias por la aclaración!

**Comment by MortizDX** [comment]
Me acaba de surgir una duda, así que reabro: comentar "prints" y "sleeps" cuentan para el descuento por statement?

**Comment by Ghoeb** [comment]
Los prints no es necesario, ya que los descartamos de todos modos. 

Los sleeps puedes comentarlos sin temor a descuentos.
