### ISSUE TITLE
Duda test para corregir

### ISSUE THREAD

**Issue by fgvenegas** [IIC2133-PUC/2017-2#76]
Hola!

Los test con los que evaluaran que tanto mas dificiles a los que nos subieron serán? Para tener una idea porque si mi test 7 se demora 4 segundos y los test de evaluación serán peores debo mejorarlo mas

Gracias!

**Comment by Ghoeb** [comment]
Es normal que demore eso: los test que se usarán para corregir serán de dificultad intermedia (los tests están en orden de dificultad)
