### ISSUE TITLE
Hay algún limite para la cantidad de operaciones?

### ISSUE THREAD

**Issue by jachicao** [IIC2133-PUC/2017-2#77]
La suma de h + w tiene algún limite?
Ej: mayor de 64?

**Comment by Ghoeb** [comment]
128 por lado, 256 en total. (por eso las operaciones son 1 byte)

**Comment by Rudyjb24** [comment]
Esto seria equivalente a decir que las matrices de los test que usaran para evaluarnos tendrán hasta 256 elementos cierto?

**Comment by Ghoeb** [comment]
Si, lo es. En state.h se ve que la matriz es de `uint8_t`, es decir, un numero sin signo de 8 bytes. Eso almacena 2^8 numeros distintos: del 0 al 255.
