### ISSUE TITLE
Test1 - Error interfaz

### ISSUE THREAD

**Issue by jtagle2** [IIC2133-PUC/2017-2#78]
Una pregunta respecto a la interfaz. Al ejecutar el test1, la interfaz nunca se me abre y el programa no me arroja ningún error. Lo raro, es que para todos los otros tests se abre y hace las operaciones y funciona perfecto. ¿Alguna idea de que puede ser? ¿A alguien más le pasa?
Estoy trabajando en Windows10

**Comment by Ghoeb** [comment]
Pasa solo con el test1?

Tienes abierto xMing?

Pusiste

```
export DISPLAY=:0
```
???

**Comment by jtagle2** [comment]
Si, hice todo lo que tiene que ver con la interfaz

**Comment by aaossa** [comment]
A mi también me pasó, pero cuando empecé a meter mano en el código y cambié el que viene no volvió a pasar 🤔
