### ISSUE TITLE
Duda sobre compilar en otro pc

### ISSUE THREAD

**Issue by roy350** [IIC2133-PUC/2017-2#8]
Hola! tengo la duda en que yo quise compilar mi programa en linux para correr valgrind ya que uso MacOSX y me dio un error al compilar, y solo lo pude solucionar borrando el archivo watcher.o ubicado en Programa/obj/watcher entonces quiero saber porque ocurre o si debo subir mi programa sin este archivo por si acaso adjunto una foto del error 
![captura de pantalla 2017-08-16 a la s 17 23 47](https://user-images.githubusercontent.com/20785160/29383781-0cdcb1ba-82a8-11e7-9c8f-727bc469aceb.png)

**Comment by Ghoeb** [comment]
Recuerda que estas en sistemas distintos, los archivos que compiles en MacOSX no te van a servir en Linux. Para limpiar los archivos compilados, usa
```
make clean
```
y luego vuelve a compilar con
```
make
```

**Comment by roy350** [comment]
Muchas gracias!

**Comment by fgvenegas** [comment]
Pero para revisar ustedes haran `make clean` o debemos pushearlo con el eso hecho?

**Comment by Ghoeb** [comment]
Es pésima práctica subir programas compilados (ya sea ejecutables o .obj), por lo que no deberian commitearlos. Pero para corregir, de todos modos haremos `make clean` para que no hayan problemas con eso.
