### ISSUE TITLE
Revisión bonus A*

### ISSUE THREAD

**Issue by sguerra2** [IIC2133-PUC/2017-2#81]
Hola!

Revisarán todas las tareas con los tests del bonus o hay que avisar que implementamos A*??

Gracias! 😉

**Comment by Ghoeb** [comment]
Voy a pedir que me envíen un mail los que quieran probar el bonus :) Aprovecho de advertir... asegurense de que A* entregue la solución optima, al igual que BFS.

**Comment by sguerra2** [comment]
Gracias!
Eso significa que si tengo revisado que el número de pasos es óptimo se sube solo el programa con A*, verdad?

**Comment by Ghoeb** [comment]
Osea, si, la tarea es una sola, y A* bien implementado es completamente superior a BFS para hacer lo mismo, por lo que si hacen A* tienen que entregar solo eso.

**Comment by sguerra2** [comment]
Yaya muchas gracias!
