### ISSUE TITLE
Cantidad de pasos minima

### ISSUE THREAD

**Issue by Rudyjb24** [IIC2133-PUC/2017-2#82]
Seria posible que para los test suban las cantidad de pasos que se debería realizar para resolver un test? Para revisar si lo que estamos haciendo esta bien.

**Comment by alopez7** [comment]
Los test (desde el 0 al 7), se solucionan en:
2
6
6
4
4
6
5
pasos

**Comment by fgvenegas** [comment]
Te falto un test parece o: porque hay 7 ahi y deberian ser 8

**Comment by alopez7** [comment]
Ups, lo corrijo altiro (debo calcularlos denuevo jajaja)

**Comment by alopez7** [comment]
Corregido
