### ISSUE TITLE
Ausencia de Informe

### ISSUE THREAD

**Issue by Rudyjb24** [IIC2133-PUC/2017-2#83]
Quería preguntar porque en esta tarea no tiene informe. Pregunto porque estoy bastante frustrado, pese a que le dedicado mucho tiempo solo estoy logrando resolver 2 tests en menos de 10 segundos y solo resuelvo 2 mas en menos de 30 segundos, en los otros casos no termina. Esto significa que es muy factible mi programa falle en todos los test de la corrección. 

En otras tareas se podía suplir fallos en los tests con el informe, que permite demostrar que trabajamos en la tarea, pero en esta ocasión posiblemente me saque un 1 pese a que he dedicado mucho tiempo en la tarea.

**Comment by fgvenegas** [comment]
Hola! 

No se si esto es legal, pero a mi algo que me sirvió mucho fue revisar si es solución cada vez que genero un nuevo estado antes de meterlo a la cola. Y si estas haciendo la función de hash con modulo (k%m), prueba usando un m grande y primo para no tener tantas colisiones. Ojala te sirva!

**Comment by alopez7** [comment]
No se pidió informe para que la tarea sea mas corta de hacer. Honestamente no hay mucho más que hacer que recorregir en el caso de que no te vaya muy bien. 
A mi criterio hay algo que debes estar haciendo mal en tu código para que se demore tanto. Es posible que tu función de hash no distribuya bien o tal vez es muy lenta de calcular. 
Te recomiendo testear la distribución de tu función de hash con los puzzles que les dimos. 

Una buena herramienta para ves en qué se demora tu código es callgrind. Te permite tener una visualización de los tiempos de tu programa. Así puede ver qué es lo que se demora más (posiblemente el cuello de botella de tu programa). 
Para usarlo debes instalar kcachegrind y ejecutar tu programa con valgring --tool=callgrind. Esto generará un archivo que puede abrir con kcachegrind.

**Comment by alopez7** [comment]
La visualización de kcachegrind es de esta forma: 
![image](https://user-images.githubusercontent.com/11396472/32305039-c28fb5bc-bf51-11e7-841d-53fa2ee590ad.png)

Las cajas son las funciones, y el tamaño de la caja reprecenta el tiempo total del programa usado en esa función. Las cajas están dentro de otras cuando son llamadas por otra función.
