### ISSUE TITLE
horario examen

### ISSUE THREAD

**Issue by lefischer** [IIC2133-PUC/2017-2#86]
Hola, 
en que horario será el examen y cuanto durará? no aparece en el programa y necesito saberlo lo antes posible puesto que tengo que inscribir horario para una presentación. 

gracias

**Comment by alopez7** [comment]
Hola
9 AM en la sala A1

**Comment by Ghoeb** [comment]
Hola, el examen _generalmente_ dura 2hrs, pero si están muy complicados lo más probable es que les demos más tiempo: puede que estemos hasta las 12...
