### ISSUE TITLE
Error al subir archivos [Recorreccion T2]

### ISSUE THREAD

**Issue by cggutierrez** [IIC2133-PUC/2017-2#88]
Hola, para la tarea 2 subi dos archivos y me equivoque en cambiarles el nombre y dejar el que queria que se corrigiera como el "main.c".

Existe la posibilidad de recorregir la tarea con el otro archivo si hago un comit en que solo cambio los nombres de ellos?

Gracias!

**Comment by pdpino** [comment]
Hola!
Sí se puede recorregir la tarea, sube un issue a tu repositorio de la tarea indicando esto mismo y haz un commit con los cambios en la rama master.

**Comment by cggutierrez** [comment]
Buena, mi otra duda es cuanto descuento tengo por que se corrija el archivo que quería que se corrigiera? o no lleva descuento? ya que podría modificar un statement de la tarea que entregue, pero no seria tan eficiente como el archivo que quería entregar.

Gracias!

**Comment by pdpino** [comment]
Convérsalo con el ayudante que verá la recorrección del código, por el mismo issue en tu repo :relaxed:

**Comment by alopez7** [comment]
Por lo de nombre no te voy a descontar nada
