### ISSUE TITLE
Dudas varias

### ISSUE THREAD

**Issue by roy350** [IIC2133-PUC/2017-2#9]
Hola quiero saber si creo una matriz es necesario hacerla dinamica con malloc o se puede hacer estatica? y el uso de punteros es obligatorio tambien? mi tarea funciona con una matriz estatica y sin punteros entonces para saber si corregirlo o no muchas gracias!

**Comment by Ghoeb** [comment]
Si efectivamente lo pudiste hacer con una matriz estática no hay problema, pero la idea es que aproveches de practicar el uso de punteros, ya que en las proximas tareas va a ser muy importante.

**Comment by roy350** [comment]
Ya, muchas gracias :) y la ultima duda, hay que mostrar directamente el resultado final o el paso a paso con un sleep y si hay que usar de cuanto tiempo seria? muchas gracias de antemano :)

**Comment by Ghoeb** [comment]
Los sleeps los vamos a eliminar: todo lo que tu envies a la ventana será registrado para la evaluación. 

Tienes que ir mostrando en pantalla cada una de las iteraciones de la simulación.

**Comment by roy350** [comment]
pero a mi se me muestra las etapas con un sleep :( de hecho no sabria como hacerlo sin el sleep ya que carga igual bien rapido que es como si se mostrara solo la ultima iteracion

**Comment by Ghoeb** [comment]
Nono, ponle el sleep para poder verlo, eso esta bien, pero recuerda que la corrección es automatizada, asique para que no se demore horas cada tarea, vamos a eliminar los sleeps.

Respecto a corregir según lo que muestras en la ventana, en realidad vamos a evaluar las llamadas a funciones del `watcher`, ya que esas controlan que es lo que se muestra.

**Comment by roy350** [comment]
me quedo clarisimo, muchas gracias por la buena disposicion a responder las dudas!
