### ISSUE TITLE
Sala examen

### ISSUE THREAD

**Issue by MortizDX** [IIC2133-PUC/2017-2#95]
Buenas, no sé si han enviado un aviso al respecto anteriormente (revisé mis correos y no encontré nada) o si lo mencionaron hoy en la ayudantía (no pude ir al coincidir con ayudantía de otro ramo), así que pregunto ¿en qué sala será el examen de mañana?

**Comment by btibarra** [comment]
9am en la sala A1 creo que salía en otro issue

**Comment by MortizDX** [comment]
Vale, gracias! (justo después mandaron un correo de todos modos XD)
